kind: pipeline
name: qt-5.12

steps:
- name: build and test
  image: nextcloudci/client-5.12:client-5.12-7
  commands:
    # Install QtKeyChain
    - /bin/bash -c "
      export CC=gcc-7 &&
      export CXX=g++-7 &&
      export QT_BASE_DIR=/opt/qt5.12.8 &&
      export QTDIR=\$QT_BASE_DIR &&
      export PATH=\$QT_BASE_DIR/bin:\$PATH &&
      export LD_LIBRARY_PATH=\$QT_BASE_DIR/lib/x86_64-linux-gnu:\$QT_BASE_DIR/lib:/usr/local/lib:\$LD_LIBRARY_PATH &&
      export PKG_CONFIG_PATH=\$QT_BASE_DIR/lib/pkgconfig:\$PKG_CONFIG_PATH &&
      cd /tmp &&
      git clone https://github.com/frankosterfeld/qtkeychain.git &&
      cd qtkeychain &&
      git checkout v0.9.1 &&
      mkdir build &&
      cd build &&
      cmake ../ &&
      make &&
      make install"
    # Build client
    - /bin/bash -c "
      export CC=gcc-7 &&
      export CXX=g++-7 &&
      export QT_BASE_DIR=/opt/qt5.12.8 &&
      export QTDIR=\$QT_BASE_DIR &&
      export PATH=\$QT_BASE_DIR/bin:\$PATH &&
      export LD_LIBRARY_PATH=\$QT_BASE_DIR/lib/x86_64-linux-gnu:\$QT_BASE_DIR/lib:/usr/local/lib:\$LD_LIBRARY_PATH &&
      export PKG_CONFIG_PATH=\$QT_BASE_DIR/lib/pkgconfig:\$PKG_CONFIG_PATH &&
      mkdir build &&
      cd build &&
      cmake -D NO_SHIBBOLETH=1 -DBUILD_UPDATER=ON -DCMAKE_BUILD_TYPE=Debug -DUNIT_TESTING=1 -DSANITIZE_ADDRESS=ON ../ &&
      make &&
      useradd -m -s /bin/bash test &&
      chown -R test:test . &&
      su -c 'ASAN_OPTIONS=detect_leaks=0 ctest --output-on-failure' test"
trigger:
  branch:
    - master
  event:
    - pull_request
    - push

---
kind: pipeline
name: qt-5.12-clang

steps:
- name: build and test
  image: nextcloudci/client-5.12:client-5.12-7
  commands:
    # Install QtKeyChain
    - /bin/bash -c "
      export CC=clang-6.0 &&
      export CXX=clang++-6.0 &&
      export QT_BASE_DIR=/opt/qt5.12.8 &&
      export QTDIR=\$QT_BASE_DIR &&
      export PATH=\$QT_BASE_DIR/bin:\$PATH &&
      export LD_LIBRARY_PATH=\$QT_BASE_DIR/lib/x86_64-linux-gnu:\$QT_BASE_DIR/lib:/usr/local/lib:\$LD_LIBRARY_PATH &&
      export PKG_CONFIG_PATH=\$QT_BASE_DIR/lib/pkgconfig:\$PKG_CONFIG_PATH &&
      cd /tmp &&
      git clone https://github.com/frankosterfeld/qtkeychain.git &&
      cd qtkeychain &&
      git checkout v0.9.1 &&
      mkdir build &&
      cd build &&
      cmake ../ &&
      make &&
      make install"
    # Build client
    - /bin/bash -c "
      export CC=clang-6.0 &&
      export CXX=clang++-6.0 &&
      export QT_BASE_DIR=/opt/qt5.12.8 &&
      export QTDIR=\$QT_BASE_DIR &&
      export PATH=\$QT_BASE_DIR/bin:\$PATH &&
      export LD_LIBRARY_PATH=\$QT_BASE_DIR/lib/x86_64-linux-gnu:\$QT_BASE_DIR/lib:/usr/local/lib:\$LD_LIBRARY_PATH &&
      export PKG_CONFIG_PATH=\$QT_BASE_DIR/lib/pkgconfig:\$PKG_CONFIG_PATH &&
      mkdir build &&
      cd build &&
      cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DNO_SHIBBOLETH=1 -DBUILD_UPDATER=ON -DCMAKE_BUILD_TYPE=Debug -DUNIT_TESTING=1 -DSANITIZE_ADDRESS=ON ../ &&
      make &&
      useradd -m -s /bin/bash test &&
      chown -R test:test . &&
      su -c 'ASAN_OPTIONS=detect_leaks=0 ctest --output-on-failure' test"
    # Static analysis with clang-tidy
    - "! run-clang-tidy-6.0 -p build -quiet | grep -A 5 ': error:'"
trigger:
  branch:
    - master
  event:
    - pull_request
    - push

---
kind: pipeline
name: AppImage

steps:
- name: build
  image: nextcloudci/client-5.12:client-5.12-7
  environment:
    CI_UPLOAD_GIT_TOKEN:
      from_secret: CI_UPLOAD_GIT_TOKEN
    CI_UPLOAD_GIT_USERNAME:
      from_secret: CI_UPLOAD_GIT_USERNAME
  commands:
    - /bin/bash -c "./admin/linux/build-appimage.sh"
    - /bin/bash -c "./admin/linux/upload-appimage.sh" || echo "Upload failed, however this is an optional step."
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
---
kind: pipeline
name: Debian

steps:
- name: build
  image: nextcloudci/client-debian-ci:client-debian-ci-2
  commands:
    - /bin/bash -c "./admin/linux/debian/drone-build.sh"
  environment:
    DEBIAN_SECRET_KEY:
      from_secret: DEBIAN_SECRET_KEY
    DEBIAN_SECRET_IV:
      from_secret: DEBIAN_SECRET_IV
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
---
kind: pipeline
name: Documentation

steps:
- name: build
  image: nextcloudci/documentation:documentation-5
  commands:
    - cd doc
    - make html
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
